# Numpy
- Numerical Python
- 고성능 수치 계산을 위한 라이브러리
- 벡터나 행렬 연산에 편리한 기능 제공
- 모든 원소는 같은 자료형만 가능

## 1. 배열 생성 및 속성 확인
    - 배열 재구성 시, 원소 개수와 새로운 배열의 크기(행 × 열) 일치 필수.

In [8]:
# a.reshape(3, 6)  # 원소 수 불일치로 오류 발생

In [31]:
import numpy as np

# 0부터 14까지 숫자로 이루어진 배열 생성
a = np.arange(15)  # np.arange(시작, 끝, 간격) (기본값: 시작=0, 간격=1)
print(a)  # 출력: [0, 1, 2, ..., 14]

# 배열을 3행 5열로 재구성 (열 기준으로 할당)
a = a.reshape(3, 5, order='F')  # np.reshape(행, 열, 할당 방식 'C' 또는 'F')
print(a)  # 출력: 3행 5열 배열 (열 기준으로 데이터 재구성)
# 출력:
# [[ 0  3  6  9 12]
#  [ 1  4  7 10 13]
#  [ 2  5  8 11 14]]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  3  6  9 12]
 [ 1  4  7 10 13]
 [ 2  5  8 11 14]]


## 2. 리스트, 튜플, 세트 변환 및 차이점
    - 리스트: 중복 허용, 순서 있음, 수정 가능
    - 튜플: 중복 허용, 순서 있음, 수정 불가
    - 세트: 중복 불허, 순서 없음

In [35]:
# 리스트 (중복 허용, 순서 있음)
b = [-1, 2, 5, -3, 0]  # 리스트 생성 [요소1, 요소2, ...]
b = np.array(b)  # 리스트를 Numpy 배열로 변환
print(type(b))  # 출력: <class 'numpy.ndarray'>

# 튜플 (변경 불가, 순서 있음)
t = (10, 20, 30)  # 튜플 생성 (요소1, 요소2, ...)
t = np.array(t)  # 튜플을 Numpy 배열로 변환
print(type(t))  # 출력: <class 'numpy.ndarray'>

# 세트 (중복 허용 안함, 순서 없음)
s = {10, 20, 30}  # 세트 생성 {요소1, 요소2, ...}
s = np.array(s)  # 세트를 Numpy 배열로 변환
print(type(s))  # 출력: <class 'numpy.ndarray'>

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


## 3. 배열 수학 연산
    - 부호가 있는 값은 np.abs()로 양수로 변환하여 계산 가능.

In [42]:
# 배열의 절대값, 제곱근, 제곱 계산
print(np.abs(b))  # 배열의 절대값 반환
# 출력: [1 2 5 3 0]

print(np.sqrt(np.abs(b)))  # 배열의 절대값의 제곱근 반환
# 출력: [1.         1.41421356 2.23606798 1.73205081 0.        ]

print(np.square(b))  # 배열의 원소들을 제곱
# 출력: [ 1  4 25  9  0]

[1 2 5 3 0]
[1.         1.41421356 2.23606798 1.73205081 0.        ]
[ 1  4 25  9  0]


## 4. NaN 처리 및 통계 함수
    - NaN 값이 포함된 배열에서 통계 연산(sum(), mean()) 시, NaN 값이 결과에 영향을 미칠 수 있음.
    - NaN 여부는 np.isnan()으로 확인할 수 있습니다.

In [50]:
# NaN 여부 확인 및 통계 연산
print(np.isnan(b))  # 배열의 NaN 여부 반환 (True/False)
# 출력: [False False False False False]

print(np.sum(b))  # 배열의 합계 계산
# 출력: 3

print(np.mean(b))  # 배열의 평균 계산
# 출력: 0.6

[False False False False False]
3
0.6


## 5. 배열 정렬
    - 슬라이싱 규칙에서 np.sort(b)[::-1] : 역순 배열.
    - 슬라이싱 (처음:끝:증감값)에서 증감값=(-1)은 배열 역순 출력.

In [54]:
# 배열 정렬 (오름차순, 내림차순)
print(np.sort(b))  # 배열을 오름차순으로 정렬
# 출력: [-3 -1  0  2  5]

print(np.sort(b)[::-1])  # 배열을 내림차순으로 정렬 (슬라이싱: 처음:끝:증감값)
# 출력: [ 5  2  0 -1 -3]

[-3 -1  0  2  5]
[ 5  2  0 -1 -3]


## 6. 다차원 배열 연산
    - axis=0 : 열 기준
    - axis=1 : 행 기준으로 연산 수행.

In [68]:
# 2차원 배열 생성 (행, 열)
c = np.array([[1, 2, 3], [4, 5, 6]])  # np.array([[행1], [행2]])
print(c)
# 출력: 2차원 배열
# [[1 2 3]
#  [4 5 6]] 

# 배열 합계 (전체, 행별, 열별)
print(np.sum(c))  # 배열의 모든 원소 합계
# 출력: 21

print(np.sum(c, axis=0))  # 열 기준으로 합계 (axis=0)
# 출력: [5 7 9]

print(np.sum(c, axis=1))  # 행 기준으로 합계 (axis=1)
# 출력: [ 6 15]

[[1 2 3]
 [4 5 6]]
21
[5 7 9]
[ 6 15]


## 7. 배열 병합 및 분할
    - 병합과 분할 시 배열의 크기 동일해야 함.
    - 분할 시 구간 명확히 지정.
      (Ex. np.hsplit(e, 3) : 배열을 3개 부분으로 나눔.


In [72]:
# 배열 병합 (수평, 수직)
c = np.random.rand(2, 2) * 100  # 임의의 값으로 채워진 2x2 배열
d = np.random.rand(2, 2) * 100
print(np.hstack((c, d)))  
# 출력:
# [[99.9 46.7 59.3 85.1]
#  [32.2 67.4 89.1 20.7]]

print(np.vstack((c, d)))  
# 출력:
# [[99.9 46.7]
#  [32.2 67.4]
#  [59.3 85.1]
#  [89.1 20.7]]

# 배열 분할 (수평 분할, 수직 분할)
e = np.random.rand(2, 15) * 100
print(np.hsplit(e, 3))
# 출력: 열을 3등분으로 수평 분할
# [array([[33.8, 11.4, 94.4, 74.9,  1.5],
#         [ 6.7,  9.9, 68.8, 71.4,  2.8]]), ...]

print(np.vsplit(e, 2))
# 출력: 배열을 2등분으로 수직 분할
# [array([[33.8, 11.4, 94.4, 74.9,  1.5, 25.7, 40.2, 85.7, 72.8, 61.8,
#         47.2, 42.3, 59.5, 40.7, 11.7]]), ...]

[[71.2876998  99.70932953 27.11339179 73.15683103]
 [91.33387165 79.35326453 93.90757114 11.83401946]]
[[71.2876998  99.70932953]
 [91.33387165 79.35326453]
 [27.11339179 73.15683103]
 [93.90757114 11.83401946]]
[array([[92.24278149, 99.66676797, 26.87536294, 67.43781656, 93.54255541],
       [62.67975802, 89.22618813, 56.71041469, 68.85917665, 61.54944583]]), array([[84.43934923, 63.89331555, 26.98177203, 82.9001444 , 40.44652253],
       [57.75700291, 38.78132762, 27.66112338, 16.76488621, 85.18594362]]), array([[31.53951874, 91.57941467, 17.61426713, 60.89551958,  4.04257249],
       [34.46521263, 80.57371339, 84.96084519, 43.10499989, 23.30919834]])]
[array([[92.24278149, 99.66676797, 26.87536294, 67.43781656, 93.54255541,
        84.43934923, 63.89331555, 26.98177203, 82.9001444 , 40.44652253,
        31.53951874, 91.57941467, 17.61426713, 60.89551958,  4.04257249]]), array([[62.67975802, 89.22618813, 56.71041469, 68.85917665, 61.54944583,
        57.75700291, 38.78132762, 27.6611

## 8. 삼항 연산
    - np.where() : 조건에 따라 참/거짓 시 반환 값 각각 지정 가능.
    - Ex. np.where(h, f, g) : h가 참일 때 f, 거짓일 때 g의 값 반환.


In [82]:
f = np.array([1, 2, 3])  # np.array([값1, 값2, 값3])
g = np.array(['A', 'B', 'C'])
h = np.array([True, False, True])

# 조건에 따른 배열 선택
print([x if z else y for x, y, z in zip(f, g, h)])  # 조건에 따른 배열 값 선택
# 출력: [1, 'B', 3]
print(np.where(h, f, g))  # 조건이 참이면 f, 거짓이면 g를 선택
# 출력: ['1' 'B' '3']

[1, 'B', 3]
['1' 'B' '3']


## 9. 파일 저장 및 불러오기
    - np.save() : 배열 저장.
    - np.load() : 배열 불러오기.
    - np.savez() : 여러 배열을 한 파일에 저장 및 이름 지정.

In [86]:
# 배열 저장 및 불러오기 (단일 파일)
i = np.arange(10)  # 0부터 9까지의 배열 생성
np.save('i.npy', i)  # 배열을 파일로 저장
ii = np.load('i.npy')  # 파일에서 배열 불러오기
print(ii)
# 출력: [0 1 2 3 4 5 6 7 8 9]

# 다중 배열 저장 및 불러오기
j = np.arange(10)
k = np.arange(20)
np.savez('jk.npz', x=j, y=k)  # 여러 배열을 한 파일에 저장
jk = np.load('jk.npz')  # 저장된 배열 불러오기
print(jk['x'])  # 'x' 배열 출력
print(jk['y'])  # 'y' 배열 출력

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
