In [1]:
# Numpy
# Numerical Python
# 고성능 수치 계산을 위한 라이브러리
# 벡터나 행렬 연산에 편리한 기능 제공
# 모든 원소는 같은 자료형만 가능

In [2]:
import numpy as np
a = np.arange(15)             # for i in rnage(!5)
print(a)

a = a.reshape(3, 5, order='F')    # .reshape(행, 열) : 차원 변경 / (기본값)C행부터 할당, F열부터 할당
print(a)
print(type(a))                # type 확인
print(a.shape)                # shape : 데이터 개수 확인 시 많이 사용
print(a.dtype)                # data type 확인
print(a.ndim)                 # 몇 차원 data인지 확인
print(a.size)

# print(dir(np))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  3  6  9 12]
 [ 1  4  7 10 13]
 [ 2  5  8 11 14]]
<class 'numpy.ndarray'>
(3, 5)
int32
2
15


In [3]:
a = a.reshape(3, 6)           # reshape 사용 시 데이터 개수 일치해야 함.

ValueError: cannot reshape array of size 15 into shape (3,6)

In [ ]:
a = np.arange(15).reshape(3, 5)       # 한 줄로 표현 가능
print(a)

## 기존 자료형을 numpyex 자료형으로 바꾸기

In [ ]:
b = [-1, 2, 5, -3, 0, 7, -9, 7, -4, -7]    # List
print(type(b))
b= np.array(b)    # List를 np로
print(type(b))

t = (10, 20, 30, 40, 50)                   # Tuple
print(type(t))
t = np.array(t)
print(type(t))

# list는 중복이 되는데 set은 중복이 안 된다?? 
s = {10, 20, 30, 40, 50}                   # Set
print(type(s))
s = np.array(s)
print(type(s))



In [ ]:
print(b.shape)                   # 1차원 데이터로 10개.
print(b.ndim)                    # 1차원 데이터
print(b.dtype)
print(b)

# print(help(np.arange))

print(np.abs(b))                 # 절대값
print(np.sqrt(np.abs(b)))        # 제곱근
print(np.square(b))              # 제곱

# b = [-1, 2, 5, -3, 0, 7, -9, 7, -4, -7, np.nan]
# [False False False False False False False False False False  True]
print(np.isnan(b))               # NaN 여부
print(np.sum(b))                 # 합계
print(np.mean(b))                # 평균
print(np.max(b))                 # 최대값
print(np.min(b))                 # 최소값
print(np.argmax(b))              # 최대값의 index
print(np.argmin(b))              # 최소값의 index
print(np.sort(b))                # 정렬 오름차순(기본값)
print(np.sort(b)[::-1])          # 정렬 내림차순 : 오름차순 정렬을 반대로 출력    # [시작 : 끝 : 증감 간격 step]
print(np.median(b))              # 중간값



In [18]:
c = [[1, 2, 3], [4, 5, 6]]
print(type(c))
print(c)

c = np.array(c)
print(type(c))
print(c)

print(np.sum(c))
print(np.sum(c, axis = 0))             # axis = 0 (행끼리)
print(np.sum(c, axis = 1))             # axis = 1 (열끼리)

print(np.mean(c)) 
print(np.mean(c, axis = 0))            # axis = 0 (행끼리)
print(np.mean(c, axis = 1))            # axis = 1 (열끼리)

print(np.median(c)) 
print(np.median(c, axis = 0))          # axis = 0 (행끼리)
print(np.median(c, axis = 1))          # axis = 1 (열끼리)


print(np.max(c)) 
print(np.max(c, axis = 0))             # axis = 0 (행끼리)
print(np.max(c, axis = 1))             # axis = 1 (열끼리)


print(np.std(c))                       # 표준편차
print(np.var(c))                       # 분산

<class 'list'>
[[1, 2, 3], [4, 5, 6]]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
21
[5 7 9]
[ 6 15]
3.5
[2.5 3.5 4.5]
[2. 5.]
3.5
[2.5 3.5 4.5]
[2. 5.]
6
[4 5 6]
[3 6]
1.707825127659933
2.9166666666666665


## element wise

In [56]:
d = [10, 20, 30, 40, 50]
# print(d + 2)                        # error : List는 int 연산 불가

d = np.array(d)
print(d + 2)


## 데이터 요소별로 동일 동작 반복해라.

e = np.array([1, 2, 3, 4, 5])         # List를 np로 변환 후 연산 가능, 연산할 리스트끼리 리스트 내 요소 개수 일치해야 하는 점 유의
print(d + e)
print(d ** 2)                         # '**' = squre = 제곱
print(d * np.sin(d))
print(d > 35)


print(np.add(d, e))
print(np.subtract(d, e))
print(np.multiply(d, e))
print(np.divide(d, e))


[12 22 32 42 52]
[11 22 33 44 55]
[ 100  400  900 1600 2500]
[ -5.44021111  18.25890501 -29.64094872  29.80452642 -13.11874269]
[False False False  True  True]
[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]


In [66]:
import numpy as np

f = np.array([[0, 1], [1, 1]])
g = np.array([[2, 0], [3, 4]])

print(f * g)

print(f @ g)                              # 행렬곱 / 0*2 + 1*3
print(np.dot(f, g))                       # 행렬곱(함수)
print(f.dot(g))                           # 행렬곱(함수 축소)

# f          g         행렬곱 
# 0 1        2 0       3(0*2 + 1*3) 4
# 1 1        3 4       5 4

[[0 0]
 [3 4]]
[[3 4]
 [5 4]]
[[3 4]
 [5 4]]
[[3 4]
 [5 4]]


In [104]:
# np 열 빈방(배열) 만들기
h = np.zeros(10)                 # 0값으로 방 (열)10개 만들기
print(h)

i = np.zeros( (5, 5) )           # Tuple로 해야 함!
print(i)

j = np.ones(10)                  # 1값으로 방 (열)10개 만들기
print(j)

# np.random.random(개수)           # 0-1 사이 x개의 난수 발생
# np.random.randint(범위 x, y)     # 균일 분포의 정수 또는 난수 1개 발생
# np.random.rand(x행, y열)         # 0-1 사이 균일 분포 난수 matrix array 생성 (2차원도 가능)
# np.random.randn                  # 가우시안 표준 정규 분포 곡선에 맞는 난수 matrix array 생성
# np.random.nomral                 # 평균, 표준편차, sample 개수

k = np.random.random(10)
print(type(k))
print(k)

k = np.random.random(10) * 100
print(k)

# k = int( np.random.random(10) * 100 )    # error : int는 하나씩만 할 수 있는데 np는 여러개라서?

k = [ int(i) for i in k]                   # 반복문을 통해 하나씩 꺼내 계산하고 int로 형 변환해서 소수점 정리하고 k에 다시 넣어라.
print(type(k))                             # 다시 List가 되어버림.
print(k)

k = np.array( [int(i) for i in k] )        # numpyex로~
print(type(k))                             
print(k)

print(np.random.randint(10, 20))          # 10-20 범위 사이의 정수 또는 난수 1개 발생
print(np.random.rand(5, 2))               # 2차원도 가능  Ex. 5행 2열

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
[0.21254057 0.03641246 0.64822912 0.50371537 0.12832616 0.41628175
 0.1177253  0.25096066 0.41367246 0.03566324]
[32.00857549  8.82873403 63.68528236 73.31860319 20.19718606 11.76377699
 37.6135097  16.04174048 18.71702121  8.43381759]
<class 'list'>
[32, 8, 63, 73, 20, 11, 37, 16, 18, 8]
<class 'numpy.ndarray'>
[32  8 63 73 20 11 37 16 18  8]
11
[[0.22329835 0.87682095]
 [0.47969233 0.51068784]
 [0.45922446 0.05848501]
 [0.34722284 0.08613734]
 [0.13770871 0.65097875]]


## 슬라이싱

### List

In [137]:
m = [ i for i in range(10, 20) ]          # 10-19까지만 나오는 점 유의!
                                          # List 만들면 자동으로 Index 발생
# 0   1   2   3   4   5   6   7   8   9
# 10  11  12  13  14  15  16  17  18  19
        # index
print( m[0 : 5] )                          # [시작 : 끝-1 : 증감 간격=기본값1]
print( m[0 : 5 : 2] )
print( m[:] )
print( m[5:] )
print( m[:-1] )                            # 이건 끝에 -1이니까 끝값 삭제됨
print( m[::-1] )                           # 간격에 -1은 거꾸로

[10, 11, 12, 13, 14]
[10, 12, 14]
[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[15, 16, 17, 18, 19]
[10, 11, 12, 13, 14, 15, 16, 17, 18]
[19, 18, 17, 16, 15, 14, 13, 12, 11, 10]


### ndarray

In [135]:
w = np.arange(10, 20)
print( w[0:5] )                             # numpyex는 ','없이 출력됨
print( w[0:5:2] )
print( w[:-2] )

[10 11 12 13 14]
[10 12 14]
[10 11 12 13 14 15 16 17]


### 2차원

In [192]:
r = [ [1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15] ]

# 3행 5열 2차원
#     0  1  2  3  4
#  0  1  2  3  4  5
#  1  6  7  8  9  10
#  2  11 12 13 14 15

print(r[2][2])   # index를 쓰는 점 유의! 
# (index가 2번인) 3행(3번째 줄)중, (index 2번인)3열의 값

print(r[:][:])
print(r[2][:])
print(r[1][:2])   # index 1번 줄에서 index'0-1'까지의 값
print(r[:2][:1])  # [[1, 2, 3, 4, 5]] # 앞의 index 2 (행)줄 추출 연산된 거에서 index 1(행) 추출 : 반드시 행, 열 순서로 되는 것이 아닌 점 유의.
# print( r[:, :] )         # error : List는 이와 같은 형식으로 사용불가.

s = np.arange(1, 16)                  # 1차원
s = np.arange(1, 16).reshape(3, 5)    # 2차원인 3행 5열로 바꿔라
print(s)


# 어디부터 어디까지 범위를 지정해서 연속으로 가져오는 법
print(s[2][2])
print(s[:][:])
print(s[2][:])
print(s[:2][:1])            # [[1 2 3 4 5]]

print(s[:2, :2])            # pring( s[행, 열] )   ************************
print(s[: , :])
print(s[:-1, :-1])          # 끝에 하나씩 빼라
print(s[2, 2])              # index2(행)의 index2(열)
print(s[::-1, ::-1])        # 행도 거꾸로, 열도 거꾸로.


# 연속하지 않는 특정 행만 지정해서 가져오는 법
print(s[ [0, 2] ])
print(s[:, [1, 3, 4]])      # 행은 전부 다, 열은 index(1, 3, 4)꺼.
print(s[ [0, 2], [3, 4] ])  # 행(0)의 열(3) / 행(3)의 열(4)


13
[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
[11, 12, 13, 14, 15]
[6, 7]
[[1, 2, 3, 4, 5]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
13
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[11 12 13 14 15]
[[1 2 3 4 5]]
[[1 2]
 [6 7]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[1 2 3 4]
 [6 7 8 9]]
13
[[15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]
[[ 1  2  3  4  5]
 [11 12 13 14 15]]
[[ 2  4  5]
 [ 7  9 10]
 [12 14 15]]
[ 4 15]


## 전치 행렬 (행/열 배치 전환)

In [201]:
print(s)                     # 3행 5열 Data
print(s.T)                   # 5행 3열 Data

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


## numpyex 결합

In [228]:
a = [1, 2, 3]
b = [4, 5, 6]

# Zip 함수
# 1        2        3
# 4        5        6
# (1,4)  (2,5)  (3,6)  Tuple로 합침.
for ab in zip(a, b) :              # zip은 바로 출력이 안 돼서 for문 실행해야 함.
    print(ab)
print(list(zip(a, b)))
print(a + b)
# print(a + 2)       # error : 리스트는 연산 더하기 적용불가
print(a *2)         # 2번 반복 (연산 곱하기 적용 아님)



(1, 4)
(2, 5)
(3, 6)
[(1, 4), (2, 5), (3, 6)]
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3]


In [234]:
c = np.floor( np.random.rand(2, 2) * 100)        
print(c)

d = np.floor( np.random.rand(2, 2) * 100)
print(d)

print(np.hstack( (c, d) ))
print(np.vstack( (c, d) ))
print(c + 2)

[[89. 76.]
 [27. 18.]]
[[87. 26.]
 [32.  3.]]
[[89. 76. 87. 26.]
 [27. 18. 32.  3.]]
[[89. 76.]
 [27. 18.]
 [87. 26.]
 [32.  3.]]
[[91. 78.]
 [29. 20.]]


## numpyex 분리

### 가로 분리

In [254]:
e = np.random.rand(2, 15) * 100
e = np.floor(np.random.rand(2, 15) * 100)    # floor : 소수점 아래 버리기
print(e)

# 방법1 : 분리할 숫자를 1개만 입력할 경우
print(np.hsplit(e, 3))                       # 3개로 분리해라.

# 방법2
for arr in np.hsplit(e, 3) :
    print(arr)

# 방법3 : 분리할 기준 숫자를 다수 입력할 경우, Tuple로 묶어서 입력한다.
for arr in np.hsplit(e, (3, 7)) :           # index 기준 [0:3] [3:7] [7:] 분리됨.
    print(arr)
    

[[33. 27. 13. 22. 76. 93. 21. 79. 94. 10. 16.  3. 27. 67. 38.]
 [92. 68. 36. 29. 74. 37. 41. 50. 12. 34. 10. 33. 57. 32. 57.]]
[array([[33., 27., 13., 22., 76.],
       [92., 68., 36., 29., 74.]]), array([[93., 21., 79., 94., 10.],
       [37., 41., 50., 12., 34.]]), array([[16.,  3., 27., 67., 38.],
       [10., 33., 57., 32., 57.]])]
[[33. 27. 13. 22. 76.]
 [92. 68. 36. 29. 74.]]
[[93. 21. 79. 94. 10.]
 [37. 41. 50. 12. 34.]]
[[16.  3. 27. 67. 38.]
 [10. 33. 57. 32. 57.]]
[[33. 27. 13.]
 [92. 68. 36.]]
[[22. 76. 93. 21.]
 [29. 74. 37. 41.]]
[[79. 94. 10. 16.  3. 27. 67. 38.]
 [50. 12. 34. 10. 33. 57. 32. 57.]]


### 세로 분리

In [265]:
e = np.random.rand(15, 2) * 100
e = np.floor(np.random.rand(2, 15) * 100)    # floor : 소수점 아래 버리기
print(e)

# 방법1 : 분리할 숫자를 1개만 입력할 경우
print(np.vsplit(e, 2))                       # 3개로 분리해라.

# 방법2
for arr in np.vsplit(e, 2) :
    print(arr)

# 방법3 : 분리할 기준 숫자를 다수 입력할 경우, Tuple로 묶어서 입력한다.
for arr in np.vsplit(e, (2, 3)) :           # index 기준 [0:3] [3:7] [7:] 분리됨.
    print(arr)
    

[[82. 48. 10. 38. 36.  8. 94.  1. 72. 51. 85. 83. 64. 52. 66.]
 [45. 92. 79. 25. 45. 77. 38. 19. 16. 29. 34. 72. 91. 70. 62.]]
[array([[82., 48., 10., 38., 36.,  8., 94.,  1., 72., 51., 85., 83., 64.,
        52., 66.]]), array([[45., 92., 79., 25., 45., 77., 38., 19., 16., 29., 34., 72., 91.,
        70., 62.]])]
[[82. 48. 10. 38. 36.  8. 94.  1. 72. 51. 85. 83. 64. 52. 66.]]
[[45. 92. 79. 25. 45. 77. 38. 19. 16. 29. 34. 72. 91. 70. 62.]]
[[82. 48. 10. 38. 36.  8. 94.  1. 72. 51. 85. 83. 64. 52. 66.]
 [45. 92. 79. 25. 45. 77. 38. 19. 16. 29. 34. 72. 91. 70. 62.]]
[]
[]


### 삼항연산

In [286]:
# 삼항연산 : 참 if 조건 else 거짓  <- 조건? 참 : 거짓
f = np.array( [1, 2, 3, 4, 5] )
g = np.array( ['A', 'B', 'C', 'D', 'E'] )
h = np.array( [True, True, False, False, True] )

# 방법 1
print( [ x if z else y for x, y, z in zip(f, g, h) ])         # 같은 인덱스끼리 묶임
# print( 리스트로 만들어 [참 if 조건 else 거짓 for 변수1, 변수2, 변수3 in 묶어 zip(묶을변수1, 묶을변수2, 묶을변수3)

# 방법 2
print(np.where(h, f, g))
print(np.where(f < 3, '작다', '크다'))   # np.where(조건, 참, 거짓)
print(np.where(h, '참', '거짓'))

[1, 2, 'C', 'D', 5]
['1' '2' 'C' 'D' '5']
['작다' '작다' '크다' '크다' '크다']
['참' '참' '거짓' '거짓' '참']


## File Open (단일.npy / 복수.npz)

In [298]:
# Open

i = np.arange(10)        # 0-9 까지 만들어라
np.save('i.npy', i)      # 파일명, 저장할 내용


#
ii = np.load('i.npy')
print(ii)
print(type(ii))           # 단일

j = np.arange(10)
k = np.arange(20)
np.savez('jk.npz', x=j, y=k)     # x이름으로 j데이터를 저장하고, y이름으로 k데이터를 저장.
jk = np.load('jk.npz')
print(type(jk))
print(jk['x'])
print(jk['y'])

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
<class 'numpy.lib.npyio.NpzFile'>
[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
